M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Tue 22 Feb 2022 07:52:55 AM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-22T07:52:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X68.6Y-119.6
X77.6Y-82.6
X86.6Y-119.6
T0
M30
